### ISSUE TITLE
Local Script, Docker & CI Builds Failing

### ISSUE THREAD

**Issue by Zedifuu** [wanadev/pontoon-debian#9]
## Quick Information
- **Operating System:** Ubuntu Linux 22.04
- **Docker Version:** 27.3.1
- **Python Version:** 3.10
- **Node Version:** 20.90
- **Build Type:** Build Script / Build Docker

## What Happened?

First off I would like to thank you for creating this project, It's super neat and well documented! Kudos!! 

Aside from the issues faced with the build script, This has helped massively to easily deploy a production instance of Pontoon, I will be submitting a merge (pull) request shortly to resolve the build script issues and allow your CI to function correctly again. 

The build script failed due to two key issues:
1. PIP Dependencies were not being properly compiled during the build process, causing failures while installing transitive deps.
2. The script attempted to copy files that no longer exist in the upstream Pontoon repository, as they had been removed or relocated due to recent refactoring.

## Expected result

The build should successfully compile all necessary dependencies and only reference files that are present in the current repository state. The script should not attempt to copy files that no longer exist in the upstream after refactoring.

## Steps to reproduce

- Clone Project
- Attempt to run any of the build scripts

### Missing pip hash compile
```py
Collecting exceptiongroup>=1.0.2 (from anyio==4.6.0->-r requirements/default.txt (line 15))
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    exceptiongroup>=1.0.2 from https://files.pythonhosted.org/packages/02/cc/b7e31358aac6ed1ef2bb790a9746ac2c69bcb3c8588b41616914eb106eaf/exceptiongroup-1.2.2-py3-none-any.whl (from anyio==4.6.0->-r requirements/default.txt (line 15))
```
### Upstream refactor Issues
```sh
cp: cannot stat 'tag-admin/': No such file or directory
cp: cannot stat 'setup.cfg': No such file or directory
```

## Notes:
I have resolved the above issues in the following PR ( https://github.com/wanadev/pontoon-debian/pull/10 )

## Priority/Severity
- [x] High (anything that impacts the normal user flow or blocks app usage)
- Medium (anything that negatively affects the user experience)
- Low (anything else e.g., typos, missing icons/translations, layout/formatting issues, etc.)

**Comment by flozz** [comment]
fixed in #10 :)
